#ifndef ENGINEDEFINES_H
#define ENGINEDEFINES_H

#ifndef ENGINE_DIST
#define ENGINE_LOGGING 1
#define ENGINE_PROFILE 0
#else
#define ENGINE_LOGGING 0
#define ENGINE_PROFILE 0
#endif

#define ENGINE_IMGUI 1
#define RENDERER2D_STATISTICS 1

#endif // !ENGINEDEFINES_H